# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

abstract_target 'defaults' do
	use_frameworks!
	pod 'Alamofire', '~> 4.0.1'
	pod 'SwiftyJSON', '~> 3.1.1'
	pod 'Kingfisher', '~> 3.2.0'

	target 'watchOS-example'
	target 'watchOS-example WatchKit Extension'
end

#target 'watchOS-example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 #use_frameworks!

  # Pods for watchOS-example

#end

target 'watchOS-example WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOS-example WatchKit App

end

#target 'watchOS-example WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for watchOS-example WatchKit Extension

#end
